/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CertificateId = IDL.Nat;
export const CategoryId = IDL.Nat;
export const WorkId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PortfolioCategory = IDL.Record({
  'id' : CategoryId,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Certificate = IDL.Record({
  'id' : CertificateId,
  'issueDate' : IDL.Text,
  'title' : IDL.Text,
  'issuingOrganization' : IDL.Text,
  'credentialUrl' : IDL.Text,
});
export const PhotographyWork = IDL.Record({
  'id' : WorkId,
  'categoryId' : CategoryId,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCertificate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [CertificateId],
      [],
    ),
  'addPhotographyWork' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, CategoryId],
      [WorkId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func([IDL.Text, IDL.Text], [CategoryId], []),
  'deleteCategory' : IDL.Func([CategoryId], [], []),
  'deleteCertificate' : IDL.Func([CertificateId], [], []),
  'deletePhotographyWork' : IDL.Func([WorkId], [], []),
  'editCategory' : IDL.Func([CategoryId, IDL.Text, IDL.Text], [], []),
  'editCertificate' : IDL.Func(
      [CertificateId, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'editPhotographyWork' : IDL.Func(
      [WorkId, IDL.Text, IDL.Text, IDL.Text, CategoryId],
      [],
      [],
    ),
  'getAllCategories' : IDL.Func([], [IDL.Vec(PortfolioCategory)], ['query']),
  'getAllCertificates' : IDL.Func([], [IDL.Vec(Certificate)], ['query']),
  'getAllWorks' : IDL.Func([], [IDL.Vec(PhotographyWork)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorksByCategory' : IDL.Func(
      [CategoryId],
      [IDL.Vec(PhotographyWork)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CertificateId = IDL.Nat;
  const CategoryId = IDL.Nat;
  const WorkId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PortfolioCategory = IDL.Record({
    'id' : CategoryId,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Certificate = IDL.Record({
    'id' : CertificateId,
    'issueDate' : IDL.Text,
    'title' : IDL.Text,
    'issuingOrganization' : IDL.Text,
    'credentialUrl' : IDL.Text,
  });
  const PhotographyWork = IDL.Record({
    'id' : WorkId,
    'categoryId' : CategoryId,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCertificate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [CertificateId],
        [],
      ),
    'addPhotographyWork' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, CategoryId],
        [WorkId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func([IDL.Text, IDL.Text], [CategoryId], []),
    'deleteCategory' : IDL.Func([CategoryId], [], []),
    'deleteCertificate' : IDL.Func([CertificateId], [], []),
    'deletePhotographyWork' : IDL.Func([WorkId], [], []),
    'editCategory' : IDL.Func([CategoryId, IDL.Text, IDL.Text], [], []),
    'editCertificate' : IDL.Func(
        [CertificateId, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'editPhotographyWork' : IDL.Func(
        [WorkId, IDL.Text, IDL.Text, IDL.Text, CategoryId],
        [],
        [],
      ),
    'getAllCategories' : IDL.Func([], [IDL.Vec(PortfolioCategory)], ['query']),
    'getAllCertificates' : IDL.Func([], [IDL.Vec(Certificate)], ['query']),
    'getAllWorks' : IDL.Func([], [IDL.Vec(PhotographyWork)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorksByCategory' : IDL.Func(
        [CategoryId],
        [IDL.Vec(PhotographyWork)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };