/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CategoryId = bigint;
export interface Certificate {
  'id' : CertificateId,
  'issueDate' : string,
  'title' : string,
  'issuingOrganization' : string,
  'credentialUrl' : string,
}
export type CertificateId = bigint;
export interface PhotographyWork {
  'id' : WorkId,
  'categoryId' : CategoryId,
  'title' : string,
  'description' : string,
  'imageUrl' : string,
}
export interface PortfolioCategory {
  'id' : CategoryId,
  'name' : string,
  'description' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type WorkId = bigint;
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCertificate' : ActorMethod<
    [string, string, string, string],
    CertificateId
  >,
  'addPhotographyWork' : ActorMethod<
    [string, string, string, CategoryId],
    WorkId
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCategory' : ActorMethod<[string, string], CategoryId>,
  'deleteCategory' : ActorMethod<[CategoryId], undefined>,
  'deleteCertificate' : ActorMethod<[CertificateId], undefined>,
  'deletePhotographyWork' : ActorMethod<[WorkId], undefined>,
  'editCategory' : ActorMethod<[CategoryId, string, string], undefined>,
  'editCertificate' : ActorMethod<
    [CertificateId, string, string, string, string],
    undefined
  >,
  'editPhotographyWork' : ActorMethod<
    [WorkId, string, string, string, CategoryId],
    undefined
  >,
  'getAllCategories' : ActorMethod<[], Array<PortfolioCategory>>,
  'getAllCertificates' : ActorMethod<[], Array<Certificate>>,
  'getAllWorks' : ActorMethod<[], Array<PhotographyWork>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorksByCategory' : ActorMethod<[CategoryId], Array<PhotographyWork>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];